config/routes.rb
Mucca::Application.routes.draw do
  devise_for :users
  resources :musics

  root 'musics#index'

end

app/models/music.rb
class Music < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :musics
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :set_music, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /musics
  # GET /musics.json
  def index
    @musics = Music.all
  end

  # GET /musics/1
  # GET /musics/1.json
  def show
    @user = current_user

    if @user.user_state
      return redirect_to action: 'new'
    end

    # params[:id] = 13
    # @music = Music.find(params[:id])
    respond_to do |format|
      format.html #show.html.erb
      format.json { render json: @music }
    end
  end

  # GET /musics/new
  def new
    @user = current_user

    if !(@user.user_state)
      params[:id] = 13
      @music_for_user = Music.find(params[:id])
      return redirect_to music_path(@music_for_user) 
    end

    # @user.user_state = true
    # @user.save

    @music = current_user.musics.build    
  end

  # GET /musics/1/edit
  def edit
  end

  # POST /musics
  # POST /musics.json
  def create
    @music = current_user.musics.build(music_params)
    @music.save

    params[:id] = 13
    @music_for_user = Music.find(params[:id])

    redirect_to music_path(@music_for_user)

    # respond_to do |format|
    #   redirect_to 'index'
    #   if @music.save
    #     # format.html { redirect_to 'show', notice: 'Music was successfully created.' }
    #     # format.json { render action: 'show', status: :created, location: @music }
    #   else
    #     format.html { render action: 'new' }
    #     # format.json { render json: @music.errors, status: :unprocessable_entity }
    #   end
    # end

  end

  # PATCH/PUT /musics/1
  # PATCH/PUT /musics/1.json
  def update
    respond_to do |format|
      if @music.update(music_params)
        format.html { redirect_to @music, notice: 'Music was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @music.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /musics/1
  # DELETE /musics/1.json
  def destroy
    @music.destroy
    respond_to do |format|
      format.html { redirect_to musics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_music
      @music = Music.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def music_params
      params.require(:music).permit(:title, :description, :musician, :imageUrl, :videoUrl, :color)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mucca</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<% flash.each do |name, msg| %>
		<%= content_tag(:div, msg, class: "alert alert-info") %>
	<% end %>
	<%= yield %>
</body>
</html>

app/views/musics/_form.html.erb
<%= form_for(@music) do |f| %>
  <% if @music.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@music.errors.count, "error") %> prohibited this music from being saved:</h2>

      <ul>
      <% @music.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :musician %><br>
    <%= f.text_field :musician %>
  </div>
  <div class="field">
    <%= f.label :imageUrl %><br>
    <%= f.text_field :imageUrl %>
  </div>
  <div class="field">
    <%= f.label :videoUrl %><br>
    <%= f.text_field :videoUrl %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.number_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/musics/edit.html.erb
<h1>Editing music</h1>

<%= render 'form' %>

<%= link_to 'Show', @music %> |
<%= link_to 'Back', musics_path %>

app/views/musics/index.html.erb
<h1>Listing musics</h1>

<%= link_to "Log Out", destroy_user_session_path, method: :delete %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Musician</th>
      <th>Imageurl</th>
      <th>Videourl</th>
      <th>Color</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @musics.each do |music| %>
      <tr>
        <td><%= music.title %></td>
        <td><%= music.description %></td>
        <td><%= music.musician %></td>
        <td><%= music.imageUrl %></td>
        <td><%= music.videoUrl %></td>
        <td><%= music.color %></td>
        <td><%= link_to 'Show', music %></td>
        <td><%= link_to 'Edit', edit_music_path(music) %></td>
        <td><%= link_to 'Destroy', music, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Music', new_music_path %>

app/views/musics/new.html.erb
<!-- <h1>New music</h1>

<%= render 'form' %>

<%= link_to 'Back', musics_path %> -->


<html lang="ko-kr">

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Mucca</title>	
	
	<%= javascript_include_tag "js/jquery-1.11.3.min.js" -%>	
	<%= javascript_include_tag "js/bootstrap.min.js" -%>		
	<%= javascript_include_tag "js/modernizr.custom.79639" -%>	
	<%= javascript_include_tag "js/colorBar" -%>		
	<%= javascript_include_tag "js/friend" -%>
	<%= javascript_include_tag "js/auth" -%>
	<%= javascript_include_tag "js/search" -%>
    <script src="https://apis.google.com/js/client.js?onload=googleApiClientReady"></script>

	<%= stylesheet_link_tag "css/font-awesome.min", :media => "all" %>
	<%= stylesheet_link_tag "css/demo", :media => "all" %>
	<%= stylesheet_link_tag "css/pfold", :media => "all" %>
	<%= stylesheet_link_tag "css/custom1", :media => "all" %>
	<%= stylesheet_link_tag "css/givecard", :media => "all" %>	
	<%= stylesheet_link_tag "css/friend", :media => "all" %>

<body class="background">

	<div class ='header'>
		<%= image_tag "img_upLine.png" , class: "mini-logo", alt:"upLine" %>
	</div>
	
	<div class="container">
		<nav class="navbar navbar-control" role="navigation">
			<ul class="nav navbar-nav navbar-right">
				<li class="nav-info">누구누구 님</li>
				<li class="nav-info">로그아웃</li>
			</ul>
		</nav>

		<div class="row clearfix">
			<div class="col-xs-4 column">

				<%= image_tag "img_logo.png" , class: "mini-logo", alt:"logo" %>
<!-- 				<img class="mini-logo" src ="img_logo.png" alt ="logo"> -->


				<button class="b-btn menu-btn">카드 주고받기</button>
				<a href="collection.html"><button class="b-btn menu-btn btn-for-down">나의 컬렉션</button></a>
				<button class="b-btn menu-btn btn-for-down flip">친구 컬렉션</button>
				<div class="panel">	
					<div class="form-group" id="search">
						<input type="text" class="form-control" id="myForm" placeholder="&#xF002; 친구를 검색해 보세요." style="font-family:Arial, FontAwesome" />
					</div>
					<div class="user">
						김지목
					</div>
					<div class="user">				
						류기현
					</div>
					<div class="user">
						현지인
					</div>
					<div class="user last-one">
						표세원
					</div>
				</div>

			</div>
			<div class="col-xs-6 column">

				<div class="give-card">
					<%= image_tag "img_label_1.png" , class: "color-bar", alt:"color-bar" %>
					<%= image_tag "img_label_1_back.png" , class: "color-bar-back", alt:"color-bar" %>

					<div class="movie-sec">
						
						<input class="find" id="query" value='빅뱅' type="text" placeholder= "&#xF002; 가수 이름이나 노래 제목을 검색해 보세요." style="font-family:Arial, FontAwesome" onkeydown="javascript:if(event.keyCode==13){search()}">

<!-- 						<div> -->
						<iframe width="480" height="280" src="" id="main_frame" src=""></iframe>

						<div class="search-sec fade in">
							<ul type="none">
								<li class="search-list">
									<div class="search-thumb">
										<%= image_tag "img_thumb_1.png" , class: "search-image", alt:"thumbnail" %>
									</div>
									<div class="search-info">
										[EXID신곡 AH-YEAH] 
									</div>
								</li>
								<li class="search-list">
									<div class="search-thumb">
										<%= image_tag "img_thumb_1.png" , class: "search-image", alt:"thumbnail" %>
									</div>
									<div class="search-info">
										[EXID신곡 AH-YEAH] 
									</div>
								</li>
								<li class="search-list">
									<div class="search-thumb">
										<%= image_tag "img_thumb_1.png" , class: "search-image", alt:"thumbnail" %>
									</div>
									<div class="search-info">
										[EXID신곡 AH-YEAH] 
									</div>
								</li>
							</ul>
						</div>	
					</div>

						<hr>
						<div class="letter-sec">
							<textarea class="letter" placeholder="노래와 관련된 내용을 입력 해 주세요.&#10;노래에 대한 개인적인 느낌도 좋고 가수에 대한 특별한 이야기도 좋아요."></textarea>
						</div>
					</div>


					<div class="send">				
						<button class="b-btn send-btn">보내기</button>					
					</div>
				</div>


				<div id="wrapperForForm">
 					<%= form_for(@music) do |f| %>
					  <% if @music.errors.any? %>
					    <div id="error_explanation">
					      <h2><%= pluralize(@music.errors.count, "error") %> prohibited this music from being saved:</h2>

					      <ul>
					      <% @music.errors.full_messages.each do |msg| %>
					        <li><%= msg %></li>
					      <% end %>
					      </ul>
					    </div>
					  <% end %>

					  <div class="field">
					    <%= f.label :title %><br>
					    <%= f.text_field :title %>
					  </div>
					  <div class="field">
					    <%= f.label :description %><br>
					    <%= f.text_area :description %>
					  </div>
					  <div class="field">
					    <%= f.label :musician %><br>
					    <%= f.text_field :musician %>
					  </div>
					  <div class="field">
					    <%= f.label :imageUrl %><br>
					    <%= f.text_field :imageUrl %>
					  </div>
					  <div class="field">
					    <%= f.label :videoUrl %><br>
					    <%= f.text_field :videoUrl %>
					  </div>
					  <div class="field">
					    <%= f.label :color %><br>
					    <%= f.number_field :color %>
					  </div>
					  <div class="actions">
						<%= f.submit %>
					  </div>					  
 					<% end %>
				</div>

				<script>
					$('.send-btn').click(function(){
						$("input[name='commit']").click();
					});
					document.getElementById('wrapperForForm').style.display = "none";
				</script>	

				<div class="col-xs-1 column">
					<div class="color-sec">
						
						<div class="outline">
							<div class="color-ball" style="background-color:#F9F6F4" data-color="1" data-hex="#F9F6F4"></div>
						</div>

						<div class="outline">
							<div class="color-ball" style="background-color:#E98B9B" data-color="2" data-hex="#E98B9B"></div>
						</div>

						<div class="outline">
							<div class="color-ball" style="background-color:#E9AC89" data-color="3" data-hex="#E9AC89"></div>
						</div>

						<div class="outline">
							<div class="color-ball" style="background-color:#ECE098" data-color="4" data-hex="#ECE098"></div>
						</div>

						<div class="outline">
							<div class="color-ball" style="background-color:#30C6E7" data-color="5" data-hex="#30C6E7"></div>
						</div>


					</div>
				</div>
			</div>
			
		</div>

	</body>
	</html>

app/views/musics/show.html.erb
<html lang="ko-kr">

	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Mucca</title>	

	<%= javascript_include_tag "js/jquery-1.11.3.min.js" -%>	
	<%= javascript_include_tag "js/bootstrap.min.js" -%>
	<%= javascript_include_tag "js/modernizr.custom.79639" -%>
	<%= javascript_include_tag "js/friend" -%>

	<%= stylesheet_link_tag "css/font-awesome.min", :media => "all" %>
	<%= stylesheet_link_tag "css/demo", :media => "all" %>
	<%= stylesheet_link_tag "css/pfold", :media => "all" %>
	<%= stylesheet_link_tag "css/custom1", :media => "all" %>
	<%= stylesheet_link_tag "css/bootstrap.min.css", :media => "all" %>	
	<%= stylesheet_link_tag "css/givecard", :media => "all" %>	
	<%= stylesheet_link_tag "css/receivecard", :media => "all" %>	
	<%= stylesheet_link_tag "css/friend", :media => "all" %>

<body>

	<div class ='header'>
		<%= image_tag "img_upLine.png" , alt:"upLine" %>		
	</div>

	<div class="container">
		<div class="row clearfix">
			<nav class="navbar navbar-control" role="navigation">
				<ul class="nav navbar-nav navbar-right">
					<li class="nav-info">누구누구 님</li>
					<li class="nav-info">로그아웃</li>
				</ul>
			</nav>
			<div class="col-xs-4 column">
				<%= image_tag "img_logo.png", class: "mini-logo" , alt:"logo" %>
				<button class="b-btn menu-btn">카드 주고받기</button>

				<a href="collection.html"><button class="b-btn menu-btn btn-for-down">나의 컬렉션</button></a>

				<button class="b-btn menu-btn btn-for-down flip">친구 컬렉션</button>
				
				<div class="panel">	
					<div class="form-group" id="search">
	                	<input type="text" class="form-control" placeholder="&#xF002; 친구를 검색해 보세요." style="font-family:Arial, FontAwesome"/>
	                </div>
					
						<div class="user">
							김지목
						</div>
						<div class="user">				
							류기현
						</div>
						<div class="user">
							현지인
						</div>
						<div class="user last-one">
							표세원
						</div>

					</div>

			</div>
			<div class="col-xs-6 column receive-body">
				<section class="main demo-1">
				
				<div id="uc-container" class="uc-container closed-card">
					<div class="uc-initial-content">
						<!-- custom content -->

						<%= image_tag "img_cardDeco.png" , class: "card-deco", alt:"card-deco" %>
						<%= image_tag "img_label_1.png", class: "receive-color-bar" , alt:"color-bar" %>

						<span class="clickme">Click me</span>
					</div>
					<div class="uc-final-content">
						<!-- custom content -->
						<div class="scrollwrap recieve-card">
						<div class="title-sec">
						</div>
						<div class="movie-sec">
							<iframe width="100%" height="300" src=<%= @music.videoUrl %> ></iframe>
						</div>
						<hr>
						<div class="letter-sec">
							<textarea class="letter receive-letter">  <%= @music.title %> </textarea>
						</div>


						</div>
						<span class="close">x</span>
					</div>
				</div>
				<p class="info"><strong>음악이</strong> 도착했어요!</p>
			</section>


					<div class="card-btns"> 
						<a href="collection.html"><button class="receive-btn b-btn">보관하기
						</button></a>
						<a href="givecard.html"><button class="b-btn receive-btn">날리기
						</button></a>
						<button class="b-btn receive-btn receive-icon"><i class="fa fa-trash-o"></i></button>
					</div>
			</div>
		</div>
	</div>

	<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
				<%= javascript_include_tag "js/jquery.pfold" -%>	

				<script type="text/javascript">
				$(function() {

					var $container = $( '#uc-container' ),
					pfold = $( '#uc-container' ).pfold({
						easing : 'ease-in-out',
						folds : 2,
						folddirection : ['right','top']
					});

					$container.find( 'span.clickme' ).on( 'click', function() {
						$('.card-deco').css('display', 'none');
						$('.receive-color-bar').css('display', 'none');
						$('.card-btns').css('display', 'block');
						$('.uc-initial-content').css('background', 'transparent');

						pfold.unfold();

					} ).end().find( 'span.close' ).on( 'click', function() {
						pfold.fold();
						$('.card-deco').css('display', 'block');
						$('.receive-color-bar').css('display', 'block');
						$('.card-btns').css('display', 'none');
						$('.uc-initial-content').css('background', 'white');


					} );

				});
				</script>


	<!-- div class="container">
		<div class="row clearfix">
			<div class="col-md-4 column">
				
				<button class="menu-btn">카드 주고받기</button>

				<a href="collection.html"><button class="menu-btn btn-for-down">나의 컬렉션</button></a>

				<button class="menu-btn btn-for-down flip">친구 컬렉션</button>
				
				<div class="panel">	
					<div class="form-group" id="search">
	                	<input type="text" class="form-control" />
	                </div>
					
					<div>
						<div>
							<p id="user">김지목</p>
						</div>
						<div>				
							<p id="user">류기현</p>
						</div>
						<div>
							<p id="user">현지인</p>
						</div>
						<div>
							<p id="user">표세원</p>
						</div>
					</div>
				</div>

			</div>
			<div class="col-md-6 column">
				<section class="main demo-1">
				
				<div id="uc-container" class="uc-container closed-card">
					<div class="uc-initial-content"> -->
						<!-- custom content -->
					
						<!-- <img class="card-deco" src="img/img_cardDeco.png" alt="card-deco">
						<img class="receive-color-bar" src="img/img_label_1.png" alt="color-bar">

						<span class="clickme">Click me</span>
					</div>
					<div class="uc-final-content"> -->
						<!-- custom content -->
						<!-- <div class="scrollwrap recieve-card">
							<div class="movie-sec">
						<video width="100%" height="300" controls>
							<source src="img/AlvaNoto-Xerrox.mp4" type="video/mp4">

								Your browser does not support the video tag.
							</video>
						</div>
						<div class="letter-sec">
							<textarea class="letter">hello world!</textarea>
						</div>


						</div>
						<span class="close">x</span>
					</div>
				</div>
				<p class="info"><strong>음악이</strong> 도착했어요!</p>
			</section>

				<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
				<script type="text/javascript" src="js/jquery.pfold.js"></script>
				<script type="text/javascript">
				$(function() {

					var $container = $( '#uc-container' ),
					pfold = $( '#uc-container' ).pfold({
						easing : 'ease-in-out',
						folds : 2,
						folddirection : ['right','top']
					});

					$container.find( 'span.clickme' ).on( 'click', function() {

						pfold.unfold();

					} ).end().find( 'span.close' ).on( 'click', function() {

						pfold.fold();

					} );

				});
				</script>
						<a href="collection.html"><button class="receive-btn">보관하기
						</button></a>
						<a href="givecard.html"><button class="receive-btn">날리기
						</button></a>
			</div>
		</div> -->
	</body>
</html>